### ISSUE TITLE
Version property missing in tmy data, causing csv parsing issues

### ISSUE THREAD

**Issue by cameroncan** [NREL/developer.nrel.gov#281] opened 2022-10-20 15:28 UTC
Since yesterday at 22:00 GMT, we've been experiencing failures in consuming the tmy data. In the CSV the last property on the first line is `Version` and is now blank. This has previously been populated. Can this property get populated again? If not, please remove from the CSV.

Here is an example request that is returning this result:
https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-tmy-download.csv?api_key=***&names=tmy&utc=false&email=***&wkt=POINT(-111.65936921%2040.31646029)&no_cache=false

**Comment by PjEdwards** [comment] 2022-10-20 19:19
Hmm, that's a bug. I'll look into it.

**Comment by PjEdwards** [comment] 2022-10-20 20:05
OK, I deployed a fix for this. Thanks for reporting!

**Closed by PjEdwards** 2022-10-20 20:05 UTC

**Comment by cameroncan** [comment] 2022-10-20 20:36
It looks like it's all good on my end now. Thank you!

**Comment by tmr08c** [comment] 2022-12-02 22:07
While we are not seeing a blank value for `version`, we are receiving `"unknown"` (where we used to receive a value).

For example:

```csv
Source,Location ID,City,State,Country,Latitude,Longitude,Time Zone,Elevation,Local Time Zone,Dew Point Units,DHI Units,DNI Units,GHI Units,Temperature Units,Pressure Units,Wind Direction Units,Wind Speed Units,Surface Albedo Units,Version
NSRDB,1123301,-,-,-,38.29,-77.7,0,121,-5,c,w/m2,w/m2,w/m2,c,mbar,Degrees,m/s,N/A,unknown
```

This isn't breaking anything for us and isn't an urgent issue, but we were curious if this is expected behavior since we previously received values. 

Please let me know if this warrants a new, separate Issue or if there is a better way to ask about this.

**Comment by PjEdwards** [comment] 2022-12-05 19:06
Thanks for the heads-up! The version should be 3.2.0. I deployed a fix to a different version bug last week. I guess I messed up something along the way. I'm working on figuring it out and fixing it now.

**Comment by PjEdwards** [comment] 2022-12-05 20:44
Ok, I found it. I had a bug in the updated code. Fixed and deployed a little while ago. Let me know if that resolves what you were seeing. Thanks again for reporting!

**Comment by tmr08c** [comment] 2022-12-05 21:10
Your fix worked for us. Thank you for the quick turnaround, @PjEdwards! 🚀
