### ISSUE TITLE
Wrong default `utc` value for psm3 data download API

### ISSUE THREAD

**Issue by tannerntannern** [NREL/developer.nrel.gov#153] opened 2020-05-13 19:10 UTC
I'm currently using the psm3 data download API, and it seems that [these docs](https://developer.nrel.gov/docs/solar/nsrdb/psm3_data_download/#request-parameters) list the incorrect default value for the `utc` parameter.

For example, this is the URL I'm hitting:
`https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?api_key=<key>&email=<email>&attributes=clearsky_ghi,solar_zenith_angle&interval=60&names=2014&wkt=POINT(-108.5449 48.5137)`

When I omit the `utc` parameter, I get the same results as when I pass `utc=false`.  And when I pass `utc=true`, I get different results.  From this information it seems that `false` is the default, but the docs say the default is `true`.  Which is correct?

**Comment by PjEdwards** [comment] 2020-05-21 20:25
Thanks for the heads up. Let me take a look.

**Comment by reger** [comment] 2020-06-25 15:55
@PjEdwards okay to close this now?

**Comment by tannerntannern** [comment] 2020-07-06 16:50
@PjEdwards @reger, I'm not sure if the behavior of the API has been changed as a result of this issue, but it now appears that `?utc=false` and `?utc=true` don't have any effect??

**Comment by PjEdwards** [comment] 2020-07-06 20:04
Yeah, this is definitely a bug in the new code. Working on a fix now, should be able to deploy this afternoon, or tomorrow latest.

**Comment by PjEdwards** [comment] 2020-07-06 21:01
OK, that fix is deployed. I ran some tests and it appears to be working as intended. Let me know if you have continued trouble.

Thanks!

**Closed** 2020-07-14 20:08 UTC
